version: '3'

services:
  rendezvous-server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./rendezvous_server.py:/app/rendezvous_server.py
    command: python rendezvous_server.py
    networks:
      - p2p-network

  peer1:
    build: .
    depends_on:
      - rendezvous-server
    volumes:
      - ./peer.py:/app/peer.py
      - ./p2p_app.py:/app/p2p_app.py
      - ./peer1-shared:/app/shared_files
      - ./peer1-downloads:/app/downloads
    command: python p2p_app.py --server rendezvous-server
    tty: true
    stdin_open: true
    networks:
      - p2p-network

  peer2:
    build: .
    depends_on:
      - rendezvous-server
    volumes:
      - ./peer.py:/app/peer.py
      - ./p2p_app.py:/app/p2p_app.py
      - ./peer2-shared:/app/shared_files
      - ./peer2-downloads:/app/downloads
    command: python p2p_app.py --server rendezvous-server
    tty: true
    stdin_open: true
    networks:
      - p2p-network

networks:
  p2p-network:
    driver: bridge